// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#ifndef EDDPROYECTO1_H
#define EDDPROYECTO1_H

#include <ngrest/common/Service.h>
#include <string>
#include "estructura.h"

//! Dummy description for the service
/*! Some detailed description of the service */
// '*location' comment sets resource path for this service
// *location: eddproyecto1
class eddproyecto1: public ngrest::Service
{
public:
    //*method: POST
    //*location: /crearCatedratico
    std::string crearCatedratico(const Catedratico& cate);
    //*method: GET
    //*location: /recorrerCatedratico
    std::string recorrerCatedratico();
    //*method: POST
    //*location: /crearCurso
    std::string crearCurso(const Curso& cur);
    //*method: POST
    //*location: /recorrerCurso
    std::string recorrerCurso();
    //*method: GET
    //*location: /getCursos
    std::string getCursos();
    //*method: POST
    //*location: /crearDia
    std::string crearDia(const Dia& dia);
    //*method: POST
    //*location: /crearSalon
    std::string crearSalon(const Salon& sal);
    //*method: POST
    //*location: /obtenerSalones
    std::list<std::string> obtenerSalones(const std::string edificio);
    //*method: POST
    //*location: /crearHora
    std::string crearHora(const Hora& hor);
    //*method: POST
    //*location: /validarLogin
    std::string validarLogin(std::string usuario, std::string password);
    //*method: GET
    //*location: /graficarMatriz
    std::string graficarMatriz();
    //*method: POST
    //*location: /crearAsignacion
    std::string crearAsignacion(const Asignacion& ass);
    //*method: POST
    //*location: /graficarAsignacion
    std::string graficarAsignacion(const std::string dia);
};


#endif // EDDPROYECTO1_H