// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#include "eddproyecto1.h"
#include <list>
#include <string.h>
#include <stdlib.h>

ArbolCatedratico ac;
ListaCursos lc;
ListaDia ld;
ListaSalon ls;
ListaHora lh;
ListaAsignacion la;

//Inicio metodos Arbol Catedratico
std::string eddproyecto1::crearCatedratico(const Catedratico& cate){
	std::string resultado;
	ac.insertarCatedratico(cate);
	resultado = "Catedratico Ingresado";
	return resultado;
}

std::string eddproyecto1::recorrerCatedratico(){
	return ac.recorrer();
}
//Fin metodos Arbol Catedratico

//Inicio metodos Lista Simple Curso
std::string eddproyecto1::crearCurso(const Curso& cur){
	std::string resultado;
	return lc.insertarCurso(cur, ac);
}

std::string eddproyecto1::recorrerCurso(){
	return "";
}

std::string eddproyecto1::getCursos(){
	return lc.linealizar(ac, lc);
}

//Fin metodos Lista Simple Curso

//Inicio metodos Lista Simple Dias
std::string eddproyecto1::crearDia(const Dia& dia){
	return ld.insertarDia(dia);
}
//Fin metodos Lista Simple Dias

//Inicio metodos Lista Doblemente Enlazada  Salon
std::string eddproyecto1::crearSalon(const Salon& sal){
	return ls.insertarSalon(sal);
}
std::list<std::string> eddproyecto1::obtenerSalones(const std::string edificio){
	return ls.buscarSalon(edificio);
}
//Fin metodos Lista Doblemente Enlazada Salon

//Inicio metodos Lista Doblemente Enlazada Hora
std::string eddproyecto1::crearHora(const Hora& hor){
	return lh.insertarHora(hor);
}
//Fin metodos Lista Doblemente Enlazada Hora

std::string eddproyecto1::validarLogin(std::string usuario, std::string password){
	std::string p = "201700893";
	if ((usuario == "admin" || usuario == "gestor") && password == p)
		return "true";
	return "false";
}

std::string eddproyecto1::graficarMatriz(){
	std::string uno = ls.buscarSalon();
	std::string dos = lh.recorrerHora("lunes");
	return dos;
}

std::string eddproyecto1::crearAsignacion(const Asignacion& ass){
	return la.insertarAsignacion(ass, ld, lc, ac, lh, ls);
}

std::string eddproyecto1::graficarAsignacion(const std::string dia){
	return la.recorrerAsignacion(dia);
}