/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author USER
 */
public class VerImagenes extends javax.swing.JFrame {

    public String[] rutas = new String[1];

    /**
     * Creates new form VerImagenes
     */
    public VerImagenes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        mostrarImagen = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jTextField9 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Grafo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jButton2.setText("Arbol");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 6, -1, -1));

        jButton3.setText("Matriz");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 6, -1, -1));

        jButton4.setText("Arbol - Matriz");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 6, -1, -1));

        jButton5.setText("Tabla");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 6, -1, -1));

        jButton7.setText("Modificar Ruta");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(888, 416, 133, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 260, 133, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 290, 133, -1));

        jLabel1.setText("Nuevo Costo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 270, -1, -1));

        jLabel2.setText("Nuevo Tiempo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 300, -1, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 320, 133, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 350, 133, -1));

        jLabel3.setText("Pais Salida");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 330, -1, -1));

        jLabel4.setText("Pais Llegada");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 360, -1, -1));

        jButton8.setText("Eliminar Ruta");
        jButton8.setEnabled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(888, 382, 133, -1));
        getContentPane().add(mostrarImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 40, 719, 652));

        jButton9.setText("Buscar Rutas");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 220, 140, -1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, 133, -1));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 60, 133, -1));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 90, 133, -1));

        jLabel5.setText("Salida");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 40, -1, -1));

        jLabel6.setText("Llegada");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 70, -1, -1));

        jLabel7.setText("Tipo");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 100, -1, -1));
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 120, 133, -1));

        jLabel8.setText("Cliente");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 130, -1, -1));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(783, 450, -1, 242));

        jTextField9.setEnabled(false);
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 150, 130, -1));

        jLabel9.setText("Opcion");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 160, -1, -1));

        jButton6.setText("Ruta Corta");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 190, 140, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            generarGrafo();
            Toolkit tool = Toolkit.getDefaultToolkit();
            String ruta = "C:\\Users\\USER\\Desktop\\Cali\\GrafoRuta.png";
            Image imagen = tool.createImage(ruta);
            mostrarImagen.setIcon(new ImageIcon(imagen.getScaledInstance(mostrarImagen.getWidth(), mostrarImagen.getHeight(), Image.SCALE_AREA_AVERAGING)));
        } catch (IOException ex) {
            Logger.getLogger(VerImagenes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            generarArbol();
            Toolkit tool = Toolkit.getDefaultToolkit();
            String ruta = "C:\\Users\\USER\\Desktop\\Cali\\Arbol.png";
            Image imagen = tool.createImage(ruta);
            mostrarImagen.setIcon(new ImageIcon(imagen.getScaledInstance(mostrarImagen.getWidth(), mostrarImagen.getHeight(), Image.SCALE_AREA_AVERAGING)));
        } catch (IOException ex) {
            Logger.getLogger(VerImagenes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // TODO add your handling code here:
            generarGrafo();
            Toolkit tool = Toolkit.getDefaultToolkit();
            String ruta = "C:\\Users\\USER\\Desktop\\Cali\\MatrizRuta.png";
            Image imagen = tool.createImage(ruta);
            mostrarImagen.setIcon(new ImageIcon(imagen.getScaledInstance(mostrarImagen.getWidth(), mostrarImagen.getHeight(), Image.SCALE_AREA_AVERAGING)));
        } catch (IOException ex) {
            Logger.getLogger(VerImagenes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            generarArbolMatriz();
            Toolkit tool = Toolkit.getDefaultToolkit();
            String ruta = "C:\\Users\\USER\\Desktop\\Cali\\ArbolMatriz.png";
            Image imagen = tool.createImage(ruta);
            mostrarImagen.setIcon(new ImageIcon(imagen.getScaledInstance(mostrarImagen.getWidth(), mostrarImagen.getHeight(), Image.SCALE_AREA_AVERAGING)));
        } catch (IOException ex) {
            Logger.getLogger(VerImagenes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            generarTabla();
            Toolkit tool = Toolkit.getDefaultToolkit();
            String ruta = "C:\\Users\\USER\\Desktop\\Cali\\TablaHash.png";
            Image imagen = tool.createImage(ruta);
            mostrarImagen.setIcon(new ImageIcon(imagen.getScaledInstance(mostrarImagen.getWidth(), mostrarImagen.getHeight(), Image.SCALE_AREA_AVERAGING)));
        } catch (IOException ex) {
            Logger.getLogger(VerImagenes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        String codigo = "0";
        String nombre = jTextField8.getText();
        String paisSalida = jTextField5.getText();
        String paisLlegada = jTextField6.getText();
        String tipo = jTextField7.getText();
        switch (tipo) {
            case "Costo":
                tipo = "1";
                break;
            case "Tiempo":
                tipo = "0";
                break;
        }
        String plan = "";
        if (jTextField9.isEnabled()) {
            try {
                //plan = obtenerRuta(paisSalida, paisLlegada, tipo);
                String n = jTextField9.getText();
                int nu = Integer.parseInt(n);
                System.out.println(rutas[nu - 1]);
                insertarTabla(codigo, nombre, "0", "0", rutas[nu - 1]);
            } catch (IOException ex) {
                Logger.getLogger(VerImagenes.class.getName()).log(Level.SEVERE, null, ex);
            }
            jTextField9.setEnabled(false);
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jButton9.setText("Buscar Ruta");
            jTextArea2.setText("");
            jTextField5.setEnabled(true);
            jTextField6.setEnabled(true);
            jTextField7.setEnabled(true);
            jTextField8.setEnabled(true);
        } else {
            try {
                String codigoLlegada = buscarPais(paisLlegada);
                String codigoSalida = buscarPais(paisSalida);
                buscarRuta(codigoSalida, codigoLlegada);
                jButton9.setText("Reservar");
                jTextField5.setEnabled(false);
                jTextField6.setEnabled(false);
                jTextField7.setEnabled(false);
                jTextField8.setEnabled(false);
                jTextField9.setEnabled(true);
            } catch (IOException ex) {
                Logger.getLogger(VerImagenes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        String paisSalida = jTextField3.getText();
        String paisLlegada = jTextField4.getText();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String costo = jTextField1.getText();
        String tiempo = jTextField2.getText();
        String paisSalida = jTextField3.getText();
        String paisLlegada = jTextField4.getText();
        try {
            String codigoLlegada = buscarPais(paisLlegada);
            String codigoSalida = buscarPais(paisSalida);
            modificar(codigoSalida, codigoLlegada, costo, tiempo);
        } catch (IOException ex) {
            Logger.getLogger(VerImagenes.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String codigo = "0";
        String nombre = jTextField8.getText();
        String paisSalida = jTextField5.getText();
        String paisLlegada = jTextField6.getText();
        String tipo = jTextField7.getText();
        switch (tipo) {
            case "Costo":
                tipo = "1";
                break;
            case "Tiempo":
                tipo = "0";
                break;
        }
        String plan = "";
        try {
            String codigoLlegada = buscarPais(paisLlegada);
            String codigoSalida = buscarPais(paisSalida);
            plan = obtenerRuta(codigoSalida, codigoLlegada, tipo);
            insertarTabla(codigo, nombre, "0", "0", plan);
        } catch (IOException ex) {
            Logger.getLogger(VerImagenes.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTextField9.setEnabled(false);
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    public void buscarRuta(String uno, String dos) throws MalformedURLException, IOException {
        URL myURL = new URL("http://localhost:8080/edd/webapi/Rutas/ObtenerRutas/1/" + uno + "/" + dos + "/0");
        HttpURLConnection connection = (HttpURLConnection) myURL.openConnection();
        connection.setRequestMethod("GET");
        connection.setDoOutput(true);
        connection.connect();
        BufferedReader reader = new BufferedReader(new InputStreamReader(connection.getInputStream()));
        StringBuilder results = new StringBuilder();
        String line;
        while ((line = reader.readLine()) != null) {
            results.append(line);
        }
        connection.disconnect();
        String base = results.toString();
        String datos[] = base.split(";");
        String mostrar = "";
        String tiempo = "";
        String costo = "";
        rutas = new String[datos.length];
        for (int i = 0; i < datos.length; i++) {
            String dato[] = datos[i].split("-");
            System.out.println(datos[i]);
            String codigo = "", ruta = "";
            String extra[] = dato[1].split(",");
            tiempo = extra[0];
            costo = extra[1];
            String paises[] = dato[0].split(",");
            for (int j = 0; j < paises.length; j++) {
                String da[] = paises[j].split(":");
                if (i == (paises.length - 1)) {
                    ruta += da[0];
                    codigo += da[1];
                } else {
                    ruta += da[0] + ",";
                    codigo += da[1] + ",";
                }
            }
            rutas[i] = ruta;
            mostrar += "Numero de Ruta: " + (i + 1) + "\nRuta: " + ruta + "\nTiempo: " + tiempo + "\nCosto: " + costo + "\n---------------------------------------\n";
        }
        jTextArea2.setText(mostrar);
    }

    public String buscarPais(String uno) throws MalformedURLException, IOException {
        URL myURL = new URL("http://localhost:8080/edd/webapi/Destinos/Nombre/" + uno);
        HttpURLConnection connection = (HttpURLConnection) myURL.openConnection();
        connection.setRequestMethod("GET");
        connection.setDoOutput(true);
        connection.connect();
        BufferedReader reader = new BufferedReader(new InputStreamReader(connection.getInputStream()));
        StringBuilder results = new StringBuilder();
        String line;
        while ((line = reader.readLine()) != null) {
            results.append(line);
        }
        connection.disconnect();
        return results.toString();
    }

    public void modificar(String uno, String dos, String tres, String cuatro) throws MalformedURLException, IOException {
        URL myURL = new URL("http://localhost:8080/edd/webapi/Rutas/Editar/" + uno + "/" + dos + "/" + tres + "/" + cuatro + "");
        HttpURLConnection connection = (HttpURLConnection) myURL.openConnection();
        connection.setRequestMethod("GET");
        connection.setDoOutput(true);
        connection.connect();
        BufferedReader reader = new BufferedReader(new InputStreamReader(connection.getInputStream()));
        StringBuilder results = new StringBuilder();
        String line;
        while ((line = reader.readLine()) != null) {
            results.append(line);
        }
        connection.disconnect();
    }

    public void insertarTabla(String uno, String dos, String tres, String cuatro, String cinco) throws MalformedURLException, IOException {
        URL myURL = new URL("http://localhost:8080/edd/webapi/Vuelos/InsertarT/" + uno + "/" + dos + "/" + tres + "/" + cuatro + "/" + cinco + "");
        HttpURLConnection connection = (HttpURLConnection) myURL.openConnection();
        connection.setRequestMethod("GET");
        connection.setDoOutput(true);
        connection.connect();
        BufferedReader reader = new BufferedReader(new InputStreamReader(connection.getInputStream()));
        StringBuilder results = new StringBuilder();
        String line;
        while ((line = reader.readLine()) != null) {
            results.append(line);
        }
        connection.disconnect();
    }

    public String obtenerRuta(String uno, String dos, String tres) throws MalformedURLException, IOException {
        URL myURL = new URL("http://localhost:8080/edd/webapi/Rutas/BuscarRutaCorta/" + uno + "/" + dos + "/" + tres);
        HttpURLConnection connection = (HttpURLConnection) myURL.openConnection();
        connection.setRequestMethod("GET");
        connection.setDoOutput(true);
        connection.connect();
        BufferedReader reader = new BufferedReader(new InputStreamReader(connection.getInputStream()));
        StringBuilder results = new StringBuilder();
        String line;
        while ((line = reader.readLine()) != null) {
            results.append(line);
        }
        String retorno = results.toString();
        connection.disconnect();
        return retorno;
    }

    public void generarTabla() throws MalformedURLException, IOException {
        URL myURL = new URL("http://localhost:8080/edd/webapi/Vuelos/Recorrer");
        HttpURLConnection connection = (HttpURLConnection) myURL.openConnection();
        connection.setRequestMethod("GET");
        connection.setDoOutput(true);
        connection.connect();
        BufferedReader reader = new BufferedReader(new InputStreamReader(connection.getInputStream()));
        StringBuilder results = new StringBuilder();
        String line;
        while ((line = reader.readLine()) != null) {
            results.append(line);
        }
        connection.disconnect();
    }

    public void generarArbolMatriz() throws MalformedURLException, IOException {
        URL myURL = new URL("http://localhost:8080/edd/webapi/Destinos/Graficar/ArbolMatriz");
        HttpURLConnection connection = (HttpURLConnection) myURL.openConnection();
        connection.setRequestMethod("GET");
        connection.setDoOutput(true);
        connection.connect();
        BufferedReader reader = new BufferedReader(new InputStreamReader(connection.getInputStream()));
        StringBuilder results = new StringBuilder();
        String line;
        while ((line = reader.readLine()) != null) {
            results.append(line);
        }
        connection.disconnect();
    }

    public void generarArbol() throws MalformedURLException, IOException {
        URL myURL = new URL("http://localhost:8080/edd/webapi/Destinos/Graficar/Arbol");
        HttpURLConnection connection = (HttpURLConnection) myURL.openConnection();
        connection.setRequestMethod("GET");
        connection.setDoOutput(true);
        connection.connect();
        BufferedReader reader = new BufferedReader(new InputStreamReader(connection.getInputStream()));
        StringBuilder results = new StringBuilder();
        String line;
        while ((line = reader.readLine()) != null) {
            results.append(line);
        }
        connection.disconnect();
    }

    public void generarGrafo() throws MalformedURLException, IOException {
        URL myURL = new URL("http://localhost:8080/edd/webapi/Rutas/Recorrerr/");
        HttpURLConnection connection = (HttpURLConnection) myURL.openConnection();
        connection.setRequestMethod("GET");
        connection.setDoOutput(true);
        connection.connect();
        BufferedReader reader = new BufferedReader(new InputStreamReader(connection.getInputStream()));
        StringBuilder results = new StringBuilder();
        String line;
        while ((line = reader.readLine()) != null) {
            results.append(line);
        }
        connection.disconnect();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerImagenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerImagenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerImagenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerImagenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerImagenes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel mostrarImagen;
    // End of variables declaration//GEN-END:variables

}
