// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#ifndef EDDPRACTICA1_H
#define EDDPRACTICA1_H

#include <ngrest/common/Service.h>
#include <string>
#include "estructuras.h"

//! Dummy description for the service
/*! Some detailed description of the service */
// '*location' comment sets resource path for this service
// *location: eddpractica1
class eddpractica1: public ngrest::Service
{
public:
	//*method: POST
	//*location: /newUsuario
	std::string crearUsuario(const Usuario& userx);
	//*method:GET
	//*location: /getUsuarios
	std::list<Usuario> getUsuarios();
	//*method: POST
	//*location: /newRecurso
	std::string crearRecurso(const Recurso& resource);
	//*method:GET
	//*location: /getRecurso
	std::list<Recurso> getRecurso();
	//*method:GET
	//*location: /getServicio
	std::list<Servicio> getServicio();
	//*method: GET
	//*location: /getRecurso/id_usuario
	std::string crearServicioUsuario(std::string userx);
};


#endif // EDDPRACTICA1_H